// <auto-generated />
using LegitBankApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LegitBankApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221122122111_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("LegitBankApp.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_address")
                        .HasColumnType("text");

                    b.Property<string>("_age")
                        .HasColumnType("text");

                    b.Property<string>("_email")
                        .HasColumnType("text");

                    b.Property<string>("_firstName")
                        .HasColumnType("text");

                    b.Property<string>("_gender")
                        .HasColumnType("text");

                    b.Property<string>("_lastName")
                        .HasColumnType("text");

                    b.Property<string>("_password")
                        .HasColumnType("text");

                    b.Property<string>("_phoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("_staffID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });
#pragma warning restore 612, 618
        }
    }
}
